#!/usr/bin/env bash
# inft-i01 — personalize a forged repo. Idempotent and non-destructive.
#
#   personalize.sh "Agent Name"     Set the marketplace name (won't clobber an
#                                   already-personalized name without --force).
#   personalize.sh --apply-owner    Build the LOCAL, gitignored AGENTS.override.md
#                                   from AGENTS.md + .hermes/owner.local.md, so the
#                                   profile loads without ever being committed.
#   Flags: --force  overwrite an existing name.
#
# Why AGENTS.override.md: Hermes injects the AGENTS.md chain from the project, and
# prefers AGENTS.override.md over AGENTS.md in the same directory — the documented
# place for a personal, gitignored override. The repo-root SOUL.md is NOT injected
# (Hermes reads SOUL.md from ~/.hermes/SOUL.md only), so a profile written there
# would never reach the agent. This script never touches ~/.hermes/SOUL.md: that is
# the owner's own global soul.
set -euo pipefail
cd "$(dirname "$0")/.."

PLACEHOLDER="iNFT i01"

say() { printf '%s\n' "$*"; }

apply_owner() {
  local prof=".hermes/owner.local.md"
  local base="AGENTS.md"
  local target="AGENTS.override.md"
  [ -f "$prof" ] || { say "✗ $prof not found. Write the owner profile there first (see owner/OWNER.example.md)."; exit 1; }
  [ -f "$base" ] || { say "✗ $base not found — are you in the repo root?"; exit 1; }

  # Ignore BEFORE writing, so the profile is never exposed for even one commit.
  if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    grep -qxF "$target" .gitignore 2>/dev/null || \
      printf '\n# personalized project prompt (contains owner profile) — local only\n%s\n' "$target" >> .gitignore
  fi

  # Regenerated from scratch every run: idempotent, and never stale when AGENTS.md
  # changes. The override REPLACES AGENTS.md for this directory, so it must be a
  # superset of it.
  {
    cat "$base"
    printf '\n---\n\n## OWNER PROFILE\n\n'
    printf '<!-- Local only. Generated by scripts/personalize.sh --apply-owner from\n'
    printf '     .hermes/owner.local.md. Edit that file and re-run; do not edit here. -->\n\n'
    cat "$prof"
  } > "$target"
  say "✓ $target written from $base + $prof (local only — this is what Hermes loads)."

  # Safety check: owner files must be ignored.
  if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    for f in "$prof" "$target"; do
      git check-ignore -q "$f" && say "  ✓ $f is gitignored" || say "  ⚠ $f is NOT ignored — do not push until fixed"
    done
  fi
  say "  (Optional, and yours alone: copying SOUL.md to ~/.hermes/SOUL.md puts this soul in"
  say "   every project. That file is your global soul — no script here writes to it.)"
}

set_name() {
  local newname="$1" force="${2:-}"
  local current
  current="$(python3 -c "import json;print(json.load(open('identity.json'))['marketplace_name'])" 2>/dev/null || echo "")"

  if [ "$current" != "$PLACEHOLDER" ] && [ -n "$current" ] && [ "$force" != "--force" ]; then
    say "✓ Already personalized as \"$current\" (idempotent; pass --force to change)."
    return 0
  fi

  python3 -c '
import json, sys
p = "identity.json"
j = json.load(open(p))
j["marketplace_name"] = sys.argv[1]
j.pop("marketplace_name_note", None)
open(p, "w").write(json.dumps(j, indent=2) + "\n")
' "$newname"
  say "✓ identity.json marketplace_name → \"$newname\""

  # Reflect the name in the metadata template (name field only; leave <...> mint fields).
  python3 -c '
import json, os, sys
p = "metadata/metadata.template.json"
if os.path.exists(p):
    j = json.load(open(p))
    j["name"] = sys.argv[1]
    open(p, "w").write(json.dumps(j, indent=2) + "\n")
' "$newname" 2>/dev/null || true

  [ -x scripts/make-manifest.sh ] && bash scripts/make-manifest.sh >/dev/null && say "✓ manifest regenerated"
  say "  Your agent answers to \"$newname\", \"iNFT\", and \"Hermes\"."
}

case "${1:-}" in
  ""|-h|--help) say "Usage: personalize.sh \"Agent Name\" [--force]  |  personalize.sh --apply-owner"; exit 0 ;;
  --apply-owner) apply_owner ;;
  *) set_name "$1" "${2:-}" ;;
esac
